[package]
name         = "ethos-zero"
version      = "7.0.1"
edition      = "2024"
rust-version = "1.89"
license      = "MIT OR Apache-2.0"
repository   = "https://github.com/LiGoldragon/ethos-zero"
description  = "Ethos schema language version zero: reads ethos, generates Rust."
publish      = false
autobins     = false
autoexamples = false
autotests    = false

[lib]
name = "ethos_zero"
path = "src/lib.rs"

[[bin]]
name = "ethos-zero"
path = "src/main.rs"

[features]
default = ["datom"]
datom = []

[dependencies]
protos      = { git = "https://github.com/LiGoldragon/protos",  rev = "e8701521a37c698d6a2eb933618b9d5d1c6f6ffb" }
datom-codec = { git = "https://github.com/LiGoldragon/datom-codec", rev = "18129314966c5043ee659de452b6f976fa319b21" }
quote       = "1"
proc-macro2 = "1"
syn         = { version = "3", features = ["full"] }
prettyplease = "0.3"
rkyv = { version = "0.8", default-features = false, features = ["std", "bytecheck", "little_endian", "pointer_width_32", "unaligned"] }

[dev-dependencies]
serde = "1"

[[test]]
name = "ethos"
path = "tests/ethos.rs"

[[test]]
name = "generated"
path = "tests/generated.rs"

[[test]]
name = "freshness"
path = "tests/freshness.rs"

[[test]]
name = "signal-without-datom"
path = "tests/signal_without_datom.rs"

[[test]]
name = "cli"
path = "tests/cli.rs"

[lints.rust]
unsafe_code = "forbid"
unused      = { level = "warn", priority = -1 }
dead_code   = "warn"
