//! The kinds `protos-kinds.ethos` declares, generated by ethos-zero into
//! `generated/protos-kinds.rs`, compile against this crate's types; each
//! concrete type the declaration associates bears the generated kind through
//! the hand-written one, and the generated association asserts it.

pub use protos::{Error, Protos, ReaderBudget};

#[path = "../generated/protos-kinds.rs"]
mod kinds;

impl kinds::Spendable for ReaderBudget {
    fn spend(&mut self) -> bool {
        protos::Spendable::spend(self)
    }
}

/// The generated capability reaches the reader's own spending.
fn spent_through<B: kinds::Spendable>(budget: &mut B) -> usize {
    let mut spent = 0;
    while budget.spend() {
        spent += 1;
    }
    spent
}

#[test]
fn a_reader_budget_spends_through_the_generated_kind_until_it_is_gone() {
    let mut budget = ReaderBudget { remaining: 3 };
    assert_eq!(spent_through(&mut budget), 3);
    assert_eq!(budget, ReaderBudget { remaining: 0 });
}
